title: AI Education Coalition
description: Regional collaboration for AI in education
theme: cayman

nav:
  - name: Home
    link: /repository/docs/index.md
  - name: Schools
    link: /repository/docs/schools.md
  - name: Resources
    link: /repository/docs/resources.md
  - name: Sparks Workbook
    link: /repository/docs/sparks.md
  - name: About
    link: /repository/docs/about.md

markdown: kramdown
kramdown:
  input: GFM
